version: '3.8'
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    
  order-service:
    build: .
    command: python order_service.py
    ports:
      - "8001:8001"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis:6379
      - DB_PATH=/app/data/simulation.db
    volumes:
      - db_data:/app/data
      - .:/app
    restart: unless-stopped
  
  inventory-service:
    build: .
    command: python inventory_service.py
    ports:
      - "8002:8002"  
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_URL=redis://redis:6379
      - DB_PATH=/app/data/simulation.db
    volumes:
      - db_data:/app/data
      - .:/app
    restart: unless-stopped

volumes:
  redis_data:
  db_data: